name: widgetbook_ffvii
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  ffvii_app:
    path: ../

  widgetbook: ^3.21.0
  widgetbook_annotation: ^3.10.0

dev_dependencies:
  # TODO: was causing version mismatch errors, need to resolve
  # flutter_test:
  #   sdk: flutter
  build_runner: ^2.4.9
  widgetbook_generator: ^3.8.0
  flutter_lints: ^5.0.0
  
  # TODO: below versions were causing version mismatch errors locally, need to resolve
  # widgetbook_generator: ^3.21.0
  # build_runner: ^2.12.2

flutter:
  uses-material-design: true
  assets:
    - ../
  # fonts:
  # - family: Reactor7 
  #   fonts:
  #     - asset: ./fonts/reactor7.ttf